version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./agent:/app/agent
      - ./ui:/app/ui
      - ./data:/app/data
    depends_on:
      - redis
      - ollama
      - chroma
    command: python agent/run.py
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data/processed:/chroma/data